"""Add new column ticker

Revision ID: 3a152b61bffb
Revises: 70d0aacbc475
Create Date: 2024-05-17 22:16:42.587954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a152b61bffb'
down_revision: Union[str, None] = '70d0aacbc475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_contents', sa.Column('ticker', sa.String(), nullable=False))
    op.add_column('articles', sa.Column('ticker', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'ticker')
    op.drop_column('article_contents', 'ticker')
    # ### end Alembic commands ###
