"""Add columns(ArticleContentOrm)

Revision ID: 5941b683ecd6
Revises: f30e11e332a4
Create Date: 2024-05-17 02:09:31.980307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5941b683ecd6'
down_revision: Union[str, None] = 'f30e11e332a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new column with the desired type
    op.add_column('article_contents', sa.Column('html_new', sa.LargeBinary(), nullable=True))
    
    # Copy data from the old column to the new column
    op.execute("UPDATE article_contents SET html_new = html")
    
    # Drop the old column
    op.drop_column('article_contents', 'html')
    
    # Rename the new column to the old column's name
    op.alter_column('article_contents', 'html_new', new_column_name='html')
    
    # Create new columns in 'articles' table
    op.add_column('articles', sa.Column('article_published_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('articles', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    
    # Create a new column with the desired type
    op.add_column('articles', sa.Column('latest_scraped_at_new', sa.DateTime(timezone=True), nullable=True))
    
    # Copy data from the old column to the new column
    op.execute('UPDATE articles SET latest_scraped_at_new = latest_scraped_at')
    
    # Drop the old column
    op.drop_column('articles', 'latest_scraped_at')
    
    # Rename the new column to the old column's name
    op.alter_column('articles', 'latest_scraped_at_new', new_column_name='latest_scraped_at')
    
    # Drop the old 'date' column
    op.drop_column('articles', 'date')
    # ### end Alembic commands ###
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new column with the original type
    op.add_column('article_contents', sa.Column('html_old', sa.VARCHAR(), nullable=True))
    
    # Copy data from the current column to the new column
    op.execute('UPDATE article_contents SET html_old = html')
    
    # Drop the current column
    op.drop_column('article_contents', 'html')
    
    # Rename the new column to the original column's name
    op.alter_column('article_contents', 'html_old', new_column_name='html')
    
    # Create a new column with the original type
    op.add_column('articles', sa.Column('latest_scraped_at_old', sa.VARCHAR(), nullable=True))
    
    # Copy data from the current column to the new column
    op.execute('UPDATE articles SET latest_scraped_at_old = latest_scraped_at')
    
    # Drop the current column
    op.drop_column('articles', 'latest_scraped_at')
    
    # Rename the new column to the original column's name
    op.alter_column('articles', 'latest_scraped_at_old', new_column_name='latest_scraped_at')
    
    # Add the old 'date' column back
    op.add_column('articles', sa.Column('date', sa.VARCHAR(), nullable=False))
    
    # Drop the new columns
    op.drop_column('articles', 'created_at')
    op.drop_column('articles', 'article_published_at')
    # ### end Alembic commands ###