"""change nullability of ArticleContentOrm.html to False

Revision ID: 70d0aacbc475
Revises: 0bd6fbec0ed9
Create Date: 2024-05-17 02:25:08.212985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d0aacbc475'
down_revision: Union[str, None] = '0bd6fbec0ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new column with the desired nullability
    op.add_column('article_contents', sa.Column('html_new', sa.BLOB(), nullable=False))
    
    # Copy data from the old column to the new column
    op.execute('UPDATE article_contents SET html_new = html')
    
    # Drop the old column
    op.drop_column('article_contents', 'html')
    
    # Rename the new column to the old column's name
    op.alter_column('article_contents', 'html_new', new_column_name='html')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new column with the original nullability
    op.add_column('article_contents', sa.Column('html_old', sa.BLOB(), nullable=True))
    
    # Copy data from the current column to the new column
    op.execute('UPDATE article_contents SET html_old = html')
    
    # Drop the current column
    op.drop_column('article_contents', 'html')
    
    # Rename the new column to the original column's name
    op.alter_column('article_contents', 'html_old', new_column_name='html')
    # ### end Alembic commands ###