"""Change column name of article table

Revision ID: d7d3ec2878fc
Revises: 065c693f7a96
Create Date: 2024-05-16 11:03:31.587865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d3ec2878fc'
down_revision: Union[str, None] = '065c693f7a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('original_id', sa.String(), nullable=True))
    op.drop_column('articles', 'original_article_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('original_article_id', sa.VARCHAR(), nullable=True))
    op.drop_column('articles', 'original_id')
    # ### end Alembic commands ###
